@startuml

(*) --> ===B1===
--> 1
--> 2
--> 3
--> ===B2===

===B1=== --> 4
--> ===B2===

===B2=== --> 5
--> ===B3===

===B1=== --> 6
--> ===B3===

===B3=== --> 7
--> 8
--> ===B4===

===B1=== --> 9
--> ===B4===

--> (*)
@enduml
